📚  update T1K docs
d3b-center/HLA-Typing-Dev pull request #5
Opened 2024-04-16 20:38 UTC by dmiller15

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have committed any related changes to the PR

2024-06-12 15:19 UTC, migbro requested changes
Two minor suggestions

2024-06-12 15:19 UTC, migbro commented on docs/T1K_README.md
> +T1K can be used for RNA-seq, WES, or WGS analysis. The default parameters are for RNA-seq. If you wish to perform a different analysis, you can change the `preset` field. That field has the following
You say the defaults are for RNAseq, but I am guessing it's also for WXS given there is a specific WGS preset

2024-06-12 15:19 UTC, migbro commented on docs/T1K_README.md
> +The reads for T1K can be delivered as either BAM or fastq. The [T1K documentation](https://github.com/mourisl/T1K/tree/v1.0.5#inputoutput) outlines the various ways in which these files can be delive
✨Now with CRAM support!✨

2024-06-12 15:31 UTC, migbro commented
@dmiller15 found a couple more requests for added info here: https://github.com/d3b-center/bixu-tracker/issues/2332#issuecomment-2032994819

2024-06-12 18:19 UTC, migbro approved these changes
Looks good, thanks!

2024-06-13 03:08 UTC, wongjessica93 approved these changes

2024-06-13 13:19 UTC, merged